name: mantenimiento_garfex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  formz: ^0.7.0
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  meta: ^1.12.0
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.5.11

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  assets:
    - .env
